In [2]:
import numpy as np

In [4]:
# Creating a 1D array from a list
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
# Creating a 2D array from a list of lists
b = np.array([[1, 2],
 [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [9]:
# Creating a 3D array from a list of lists of lists
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
a = np.array([[1, 0, 0],
 [1, 1, 1],
 [2, 0, 0]])
b = np.array([[1, 1, 1],
 [1, 1, 2],
 [1, 1, 2]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)



[[2 1 1]
 [2 2 3]
 [3 1 2]]
[[ 0 -1 -1]
 [ 0  0 -1]
 [ 1 -1 -2]]
[[1 0 0]
 [1 1 2]
 [2 0 0]]
[[1.  0.  0. ]
 [1.  1.  0.5]
 [2.  0.  0. ]]


In [14]:
a = np.array([[1, 0, 0],
 [1, 1, 1],
 [2, 0, 0]])
print(a)
print(np.max(a))
print(np.min(a))
print(np.average(a))

[[1 0 0]
 [1 1 1]
 [2 0 0]]
2
0
0.6666666666666666
