In [3]:
import numpy as np

In [32]:
# 1d slicing
a = np.array([55, 56, 57, 58, 59, 60, 61])

In [7]:
print(a[:])

[55 56 57 58 59 60 61]


In [9]:
print(a[3:])

[58 59 60 61]


In [11]:
print(a[::2])

[55 57 59 61]


In [13]:
print(a[::-1])

[61 60 59 58 57 56 55]


In [30]:
print(a[:1:-2])
print (a.shape)
print (a.ndim)


[4]
(4,)
1


In [15]:
print(a[-1:1:-2])

[61 59 57]


In [17]:
# multidimensional slicing
a = np.array([[0, 1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11],
 [12, 13, 14, 15]])

In [19]:
print(a[:, 2])

[ 2  6 10 14]


In [21]:
print(a[1, :])

[4 5 6 7]


In [23]:
print(a[1, ::2])

[4 6]


In [25]:
print(a[:, :-1])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [27]:
print(a[:-2])

[[0 1 2 3]
 [4 5 6 7]]


In [33]:
# broadcasting
a = np.array([1, 2, 3, 4])
print(a.ndim)

b = np.array([[2, 1, 2], [3, 2, 3], [4, 3, 4]])
print(b.ndim)

c = np.array([[[1, 2, 3], [2, 3, 4], [3, 4, 5]],
 [[1, 2, 4], [2, 3, 5], [3, 4, 6]]])
print(c.ndim)

1
2
3


In [34]:
'''You have data for a variety of professions, and you want to increase the salaries of just the data scientists by 10 
percent every other year.'''

'You have data for a variety of professions, and you want to increase the \nsalaries of just the data scientists by 10 percent every other year. Listing 3-11 \npresents the code.'

In [44]:
## Data: yearly salary in ($1000) [2025, 2026, 2027]
dataScientist = [130, 132, 137]
productManager = [127, 140, 145]
designer = [118, 118, 127]
softwareEngineer = [129, 131, 137]
employees = np.array([dataScientist,
 productManager,
 designer,
 softwareEngineer])


In [45]:
employees[0,::2]=employees[0,::2]*1.1
print(employees)

[[143 132 150]
 [127 140 145]
 [118 118 127]
 [129 131 137]]
