In [3]:
import numpy as np

In [4]:
# 1d slicing
a = np.array([55, 56, 57, 58, 59, 60, 61])

In [7]:
print(a[:])

[55 56 57 58 59 60 61]


In [9]:
print(a[3:])

[58 59 60 61]


In [11]:
print(a[::2])

[55 57 59 61]


In [13]:
print(a[::-1])

[61 60 59 58 57 56 55]


In [14]:
print(a[:1:-2])

[61 59 57]


In [15]:
print(a[-1:1:-2])

[61 59 57]


In [17]:
# multidimensional slicing
a = np.array([[0, 1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11],
 [12, 13, 14, 15]])

In [19]:
print(a[:, 2])

[ 2  6 10 14]


In [21]:
print(a[1, :])

[4 5 6 7]


In [23]:
print(a[1, ::2])

[4 6]


In [25]:
print(a[:, :-1])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [27]:
print(a[:-2])

[[0 1 2 3]
 [4 5 6 7]]


In [28]:
# broadcasting
a = np.array([1, 2, 3, 4])
print(a.ndim)

b = np.array([[2, 1, 2], [3, 2, 3], [4, 3, 4]])
print(b.ndim)

c = np.array([[[1, 2, 3], [2, 3, 4], [3, 4, 5]],
 [[1, 2, 4], [2, 3, 5], [3, 4, 6]]])
print(c.ndim)

1
2
3
